---
resources:
- name: Tuesday-9am
  type: time
  source:
    start: 9:00 AM
    stop: 11:00 AM
    interval: 1h
    location: America/Los_Angeles

- name: git-hackday
  type: git
  source:
    uri: https://github.com/cynic89/hackday.git
    branch: master

jobs:
- name: notify
  plan:
  - get: Tuesday-9am
    trigger: true
  - get: git-hackday
  - task: run-hack-day
    file: git-hackday/pipeline/notifier.yml
